# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dientitosApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dientitosApp
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'JGProgressHUD'

    pod 'FacebookCore'
    pod 'FacebookLogin'

    
  target 'dientitosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dientitosAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
